server:
  port: 8080

spring:
#  profiles.active: dev
  profiles.active: production
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

---

spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:hardwareAccDevDB
    username: h2DevDB
    password: secretPass159753
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
  flyway:
    locations: classpath:db/migration/h2

---

spring:
  profiles: production
  devtools:
    add-properties: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: hardwarePostgresDB
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
  h2:
    console:
      enabled: false
  flyway:
    locations: classpath:db/migration/postgres