spring:
  profiles:
#    active: prod
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

---

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: h2DB
    password: secretPass159753
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

---

spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect