server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
    favicon:
      enabled: false
  profiles:
    default: "dev"

---

spring:
  datasource:
    url: jdbc:h2:mem:hardwareAccDevDB
    username: h2DevDB
    password: pa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
  flyway:
    locations: classpath:db/migration/h2
  config:
    activate:
      on-profile: "dev"

---

spring:
  devtools:
    add-properties: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${HARDWARE_ACCOUNTING_DB_USER}
    password: ${HARDWARE_ACCOUNTING_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: false
  flyway:
    locations: classpath:db/migration/postgres
  config:
    activate:
      on-profile: "production"